/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.PriorityQueue;

public class App {
  /**
   * heap sort impl
   *
   * @param arr Sortable array
   */
  public static void sort(int[] arr) {
    PriorityQueue<Integer> queue = new PriorityQueue<Integer>();

    for (int i = 0; i < arr.length; i++) {
      queue.add(arr[i]);
    }

    for (int i = 0; i < arr.length; i++) {
      arr[i] = queue.poll();
    }
  }
}
